kind: Application

spring:
  application:
    name: IBC Partners
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    baseline-on-migrate: true
    enabled: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET}
    expiration: 3600000
